# Generated by Django 5.0 on 2024-01-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField()),
                ('logo', models.ImageField(upload_to='')),
                ('status', models.CharField()),
            ],
        ),
    ]
