# Generated by Django 5.0 on 2024-01-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_quantity',
            field=models.IntegerField(),
        ),
    ]
