# Generated by Django 5.0 on 2024-02-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_systemsettings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.TextField(choices=[('In stock', 'In stock'), ('On backorder', 'On backorder'), ('In transit', 'In transit'), ('Allocated', 'Allocated'), ('Shipped', 'Shipped')]),
        ),
    ]
